//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
    
    
/// <summary>
///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
/// </summary>
// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
// à l'aide d'un outil, tel que ResGen ou Visual Studio.
// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
// avec l'option /str ou régénérez votre projet VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class IconResources {
        
    private static global::System.Resources.ResourceManager resourceMan;
        
    private static global::System.Globalization.CultureInfo resourceCulture;
        
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal IconResources() {
    }
        
    /// <summary>
    ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.IconResources", typeof(IconResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
        
    /// <summary>
    ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
    ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/bad.psd.
    /// </summary>
    internal static string ICON_BAD {
        get {
            return ResourceManager.GetString("ICON_BAD", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/build.psd.
    /// </summary>
    internal static string ICON_BUILD {
        get {
            return ResourceManager.GetString("ICON_BUILD", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/dig.psd.
    /// </summary>
    internal static string ICON_DIG {
        get {
            return ResourceManager.GetString("ICON_DIG", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/food.psd.
    /// </summary>
    internal static string ICON_FOOD {
        get {
            return ResourceManager.GetString("ICON_FOOD", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/good.psd.
    /// </summary>
    internal static string ICON_GOOD {
        get {
            return ResourceManager.GetString("ICON_GOOD", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/imp.psd.
    /// </summary>
    internal static string ICON_IMP {
        get {
            return ResourceManager.GetString("ICON_IMP", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/money.psd.
    /// </summary>
    internal static string ICON_MONEY {
        get {
            return ResourceManager.GetString("ICON_MONEY", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/monster.psd.
    /// </summary>
    internal static string ICON_MONSTER {
        get {
            return ResourceManager.GetString("ICON_MONSTER", resourceCulture);
        }
    }
        
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Assets/ActionCardAsset/trap.psd.
    /// </summary>
    internal static string ICON_TRAP {
        get {
            return ResourceManager.GetString("ICON_TRAP", resourceCulture);
        }
    }
}

